---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPU-Emulator-Memory
no_index:
  directory:
    - t
    - inc
requires:
  IO::File: 0
  IO::Scalar: 0
  Scalar::Util: 0
resources: {}
version: 1.1003
x_resource: {}
